### ISSUE TITLE
list active process/window

### ISSUE THREAD

**Issue by yehosef** [rgcr/m-cli#1]
It would be great if you could have it output the current active application and window name.

**Comment by rgcr** [comment]
Hello @yehosef,  could you please explain to me your idea a little bit more?

Do you want a list like this with the window names and the processes that they are running ?
````
window  Process
  X1     a
         b

  X2     c     
```
Have I misunderstood anything? If so, please let me know. 

Feel free to create a pull request with this enhancement 👍

**Comment by yehosef** [comment]
What I'm really looking for is a way to poll the script every second or so to get the active window name so I can create my own "rescuetime" type reporting.   

http://stackoverflow.com/questions/2845483/which-command-line-tools-can-i-use-to-get-the-currently-active-application-win
https://gist.github.com/medmunds/60f79041b30060cf24d6

I tried doing it but I didn't succeed.

It could be it will also be useful to be able to list the open applications and their windows.. that sounds neat.  But my specific need is just the top/active window with its name. Eg , not just "Chrome" - but "Chrome - www.stackoverflow.com/abc123"

**Comment by oleander** [comment]
Take a look at `lsappinfo`, I think that might solve the problem.

**Comment by rgcr** [comment]
That's great, I was trying to do it with a swift script, but I think this is better.

**Comment by oleander** [comment]
If you want to stick with the "It only uses OS X commands" and "It doesn't install 3rd party tools because it doesn't have dependencies", `lsappinfo` would be the way to go. Let me know if you need any help with that or any other internal command for OS X (<= 10.11.x).

**Comment by bensleveritt** [comment]
@rgcr Is this still being considered? Feels like it might be out of scope for `m`, but it's your call.

**Comment by bensleveritt** [comment]
I'm going to close this, as I think parsing the output from `lsappinfo` is lots to work with, and I'm not sure it's quite inline with `m`s main usecases. Feel free to reopen if you haven't solved this problem, and I'll put it into the backlog
