### ISSUE TITLE
Wallpaper is not set

### ISSUE THREAD

**Issue by konstantinkobs** [rgcr/m-cli#100]
Whenever I want to change my wallpaper I would assume to navigate to the directory where the desired image file is located and then run `m wallpaper ./image.jpg`. However, when the command is run the dock disappears for a moment (restarting the Finder I guess) and the wallpaper is changed to the default wallpaper of macOS. The image which was mentioned in the command is not used.
I have not found any issue related to this problem so there are two possibilities: I am not using the command correctly or there is an issue in the project nobody before me has found. Also there could be a bug that only shows up on my machine.

**Comment by rgcr** [comment]
Hello @konstantinkobs, you were right, there was an bug on this. It is already fixed, I will update the `brew` formula soon, meanwhile you can install the latest version using the manual steps. 👍
