### ISSUE TITLE
won't clean trash on 10.11.6 (el capitan)

### ISSUE THREAD

**Issue by tallinn-code** [rgcr/m-cli#109]
Hello!

When I'm trying to clean my trash using `m trash clean` it's saying "Done!", however, my trash icon still shows all files being in trashbin.

How can I debug and fix this ?

**Comment by tallinn-code** [comment]
I do confirm that trash cleaning is indeed not working in El Capitan.

**Comment by rgcr** [comment]
if you used `brew` to install it then run this command  `bash -x /usr/local/Cellar/m-cli/{{version}}/trash clean`  (just change the right version that you are using) and let me know what was the output because the command is working fine in my mac

**Comment by tallinn-code** [comment]
Here's the terminal output: 

```
➜  m-cli bash -x /usr/local/Cellar/m-cli/0.2.3/bin/m trash clean
+ export MPATH=/usr/local/Cellar/m-cli/0.2.3
+ MPATH=/usr/local/Cellar/m-cli/0.2.3
+ case $1 in
+ COMMAND=trash
+ shift
+ '[' '!' -f /usr/local/Cellar/m-cli/0.2.3/plugins/trash ']'
+ /usr/local/Cellar/m-cli/0.2.3/plugins/trash clean
Done!
```

**Comment by rgcr** [comment]
@tallinn-code please run `bash -x /usr/local/Cellar/m-cli/0.2.3/plugins/trash clean` because the previous output was the debug info of the `m` script

**Comment by tallinn-code** [comment]
Still nothing, I mean, files are still accessible to be restored back to original locations.

Below goes the terminal output:

```
➜  ~ bash -x /usr/local/Cellar/m-cli/0.2.3/plugins/trash clean
+ case $1 in
+ clean_trash
+ '[' '!' -e /Users/shark/.Trash ']'
+ sudo chflags -R nouchg /Users/shark/.Trash/arch-anywhere-2.2.7-1-dual.iso /Users/shark/.Trash/hyper-1.3.1.dmg /Users/shark/.Trash/pdf_data_2017_04_18_14_50_raw.csv /Users/shark/.Trash/void-live-x86_64-musl-20170220-xfce.iso
Password:
+ sudo rm -rf /Users/shark/.Trash/arch-anywhere-2.2.7-1-dual.iso /Users/shark/.Trash/hyper-1.3.1.dmg /Users/shark/.Trash/pdf_data_2017_04_18_14_50_raw.csv /Users/shark/.Trash/void-live-x86_64-musl-20170220-xfce.iso
+ echo 'Done!'
Done!
```

**Comment by rgcr** [comment]
Try to run these commands and see what happens because I don't see any error and `trash` command works fine on my mac.

```
sudo chflags -R nouchg /Users/shark/.Trash/arch-anywhere-2.2.7-1-dual.iso /Users/shark/.Trash/hyper-1.3.1.dmg /Users/shark/.Trash/pdf_data_2017_04_18_14_50_raw.csv /Users/shark/.Trash/void-live-x86_64-musl-20170220-xfce.iso
```

```
sudo rm -rf /Users/shark/.Trash/arch-anywhere-2.2.7-1-dual.iso /Users/shark/.Trash/hyper-1.3.1.dmg /Users/shark/.Trash/pdf_data_2017_04_18_14_50_raw.csv /Users/shark/.Trash/void-live-x86_64-musl-20170220-xfce.iso
```

**Comment by tallinn-code** [comment]
Finally I'm sure why some files can't be deleted. The problem is that m-cli can't delete files on removable drives and mounted encrypted drives.

**Comment by tallinn-code** [comment]
@rgcr this issue is no longer an issue 😄
