### ISSUE TITLE
Add flightmode plugin for use

### ISSUE THREAD

**Issue by Jahhein** [rgcr/m-cli#112]
The command `m flightmode ` was unavailable to me using version 0.2.3 HEAD installed via Homebrew. I checked the tar file and flightmode plugin isn't in there.

Edit: I mistakenly made this an issue to remove flightmode from README as it didn't exist and thought it was an old remnant from previous versions. However it was recently added and looked further into what was the cause of it missing.

**Comment by hunter2** [comment]
Looks like the plugin is available if cloned directly and installed, but the latest release (0.2.3) doesn't include the plugin yet. Maybe time for a new release @rgcr? Also, #115 includes a commit for adding `flightmode` to the command list in the README (accidentally added to that pull request, but it's just a simple text change.

**Comment by rgcr** [comment]
Same issue #117 
I created a PR for this: https://github.com/Homebrew/homebrew-core/pull/17373

**Comment by rgcr** [comment]
The PR has been merged, just upgrade `m-cli` to the latest version.
