### ISSUE TITLE
`m screensaver` doesn't work on macOS 10.13 Beta

### ISSUE THREAD

**Issue by underyx** [rgcr/m-cli#114]
```sh
$ m screensaver
The file /System/Library/Frameworks/ScreenSaver.framework/Versions/A/Resources/ScreenSaverEngine.app does not exist.
```

**Comment by hunter2** [comment]
I'm not on High Sierra so I can't test it, but does running `open /System/Library/Frameworks/ScreenSaver.framework/Resources/ScreenSaverEngine.app` return the same error? That might be a simple fix. (The resources folder is aliased to the current version, so if High Sierra has a new version this would work across versions.)

**Comment by underyx** [comment]
@hunter2 no, that's not it, apparently it was moved to `/System/Library/CoreServices/ScreenSaverEngine.app` instead. I can start the screensaver with `open /System/Library/CoreServices/ScreenSaverEngine.app`.

**Comment by hunter2** [comment]
Okay. In that case the screensaver script is gonna need version-checking code (or the messy way, just try to execute both and suppress the "file not found". I think the best way would be to check which file exists and execute whichever is there.

**Comment by hunter2** [comment]
@rgcr I don't think #115 actually fixes this issue. I can't test, but @underyx mentioned `ScreenSaverEngine.app` was moved, so the script will require version checking code. I have created a new pull request #116 (I cannot test 10.13, it should in theory fix the issue).
