### ISSUE TITLE
Please update homebrew release

### ISSUE THREAD

**Issue by Jigsaw-Jams** [rgcr/m-cli#117]
The Homebrew release needs to be updated. 
* I didn't check to see what release brew is using, but I realized it was outdated when I went to run `m finder showpath YES`
* See #112 as well.

**Comment by rgcr** [comment]
I created a PR for this.
https://github.com/Homebrew/homebrew-core/pull/17373

**Comment by rgcr** [comment]
The PR has been merged, `m finder showpath` is available now, just upgrade `m-cli` to the latest version.

**Comment by Jigsaw-Jams** [comment]
Thanks a lot @rgcr !
