### ISSUE TITLE
add - command completion

### ISSUE THREAD

**Issue by rootscript** [rgcr/m-cli#123]
I love this tool for macOS.  Can i suggest/request an enhancement feature:

It would be useful to have command completion, to speed up workflow.

For example, typing `m bl` + `Tab` would complete to `m bluetooth`, and another `Tab` would give you the `status`, `enable`, `disable` command options.

Another example is typing `m b` + `Tab`, this would allow you to complete to `battery` or `bluetooth`

Maybe this is already implemented, or there is a Mac terminal way to index commands for auto completion? But if it is, it was not immediately obvious to me.

**Comment by rootscript** [comment]
Just noticed this: `
# copy this file into /usr/local/etc/bash_completion.d/`

**Comment by lavadew** [comment]
try the following command:

`sudo echo "complete -o bashdefault -o default -F _m m" >> /usr/local/m-cli/m`

**Comment by lavadew** [comment]
Change into the 'completion/bash' directory and run the following command:

`sudo cp m /usr/local/etc/bash_completion.d/m`

**Comment by gregorynicholas** [comment]
@lavadew perhaps should be advised without the sudo:
`cp m /usr/local/etc/bash_completion.d/m`

**Comment by bensleveritt** [comment]
@rootscript Did this work for you? I'm going to close this now, but if you still have issues, please reopen.
