### ISSUE TITLE
Release

### ISSUE THREAD

**Issue by vitkabele** [rgcr/m-cli#144]
Hi, could you please tag a new stable release? The one available over Homebrew is still 0.2.5 and this is almost 2 years ago.
@rgcr

**Comment by rgcr** [comment]
I'm working on it

**Comment by phazei** [comment]
How's that going?

**Comment by rgcr** [comment]
Sorry I've had a lot of work, but I'm catching up with this and I will release a new version very soon

**Comment by JimDabell** [comment]
@rgcr, perhaps you could add a second person as a maintainer so that they can make a release if you don’t have the time to do it?

**Comment by bensleveritt** [comment]
👋 I'm picking up this, and hopefully we'll get a new release out soon™️ I'm just checking all the changes that have happened, will put it into the changelog, and then test. I ought to put this somewhere public...

**Comment by bensleveritt** [comment]
v0.3.0 is out, so I'm closing. Sorry for the wait
