### ISSUE TITLE
brew version m wallpaper black screen no dock and can't fullscreen apps

### ISSUE THREAD

**Issue by MichaelSDavid** [rgcr/m-cli#146]
I am very angry at this and I might have to go back to a system backup to restore this. The wallpaper picture did exist. Why did this happen?

macOS 10.14.6

**Comment by MMichael789** [comment]
UPDATE: I read online that trashing ~/Library/Application Support/Dock and restarting worked, and it worked for me too. People said that this happens with corrupted image files, however, I've set this image as my background many times before the normal way in System Preferences. I still don't know why this happened.

**Comment by theomarkkuspaul** [comment]
Ran into the same error. This broke my CMD + TAB app switcher as well.

**Comment by wviana** [comment]
Trashed `~/Library/Application Support/Dock` as @MMichael789  said. It fixed at the same moment.

**Comment by jeromefaria** [comment]
Installed this moments ago and managed to immediately run into the same issue. Thanks @MMichael789 for the fix!

**Comment by phazei** [comment]
This also happens in Catalina 10.15

Breaks expose as well

**Comment by JimDabell** [comment]
It looks like the data in `desktoppicture.db` is expected to be in a different format now.

The SQLite code unconditionally sets every value to the filename.  This breaks a lot of things.

A working data set is as follows:

```
value
-------------------------------------------------------
/System/Library/Desktop Pictures/Solid Colors
0
/System/Library/Desktop Pictures/Solid Colors/Black.png
```

This can be fixed with:

`sqlite3 ${HOME}/Library/Application\ Support/Dock/desktoppicture.db "update data set value = '${1}' limit 1 offset 2" && killall Dock`

**Comment by kmalinich** [comment]
Installed it, changed the wallpaper via `m wallpaper`, Dock and Expose are cooked. C'mon homie.

**Comment by bensleveritt** [comment]
Thanks for raising this issue. The previous release 0.2.5 was old, so I've made a new release. I'll update this command with @JimDabell's work, though I'll need a brave soul to verify it for me

**Comment by bensleveritt** [comment]
In fact, the latest version (0.3.0) uses a different strategy (Applecscript) which is far less dangerous #133. I'll close for now, but if there are any issues, feel free to reopen
