### ISSUE TITLE
Setting wallpaper has broken desktop prefs

### ISSUE THREAD

**Issue by timkinnane** [rgcr/m-cli#149]
I used the `m wallpaper` command and it did something to my desktop config that has completely borked it. Steps to reproduce:
- Install m-cli with brew
- Play around with commands - probably bad...
  - `m wallpaper -h`
  - `m wallpaper /tmp/snapshot.png`
  - `m wallpaper "/tmp/snapshot.png"`
- Wallpaper removed (black)
- Things are broken
  - Can't set wallpaper, even through system prefs
  - Hot corners also gone and can't be selected
  - Command+tab functionality also gone
- Panic and uninstall - unsurprisingly, did not fix

**Comment by falquaddoomi** [comment]
@timkinnane FYI, this issue has a fix: https://github.com/rgcr/m-cli/issues/146.

Basically, enter `rm ~/Library/Application\ Support/Dock/desktoppicture.db` and the Dock should come back to life.

**Comment by timkinnane** [comment]
Thanks so much @falquaddoomi - that fixed it. I don't know why I didn't find that issue before.
Closing this as dupe of #146
