### ISSUE TITLE
MacPorts

### ISSUE THREAD

**Issue by gracjankn** [rgcr/m-cli#150]
Hi!

I was using the tool via Homebrew, but a few days ago I switched to MacPorts. It seems it doesn't exist in their repos, so want to ask, if you'd be willing to add it. If so, it'd be very appreciated.

If not, maybe I could do that (I don't know how to do that yet, but I could find out) or maybe there's other contributor here who has more experience with MacPorts and knows how to do it (if such person is reading this, please respond to this issue).

Thank you in advance and have a great day!

**Comment by bensleveritt** [comment]
Interesting proposal!

I use Homebrew, but have started moving to darwin-nix. I think there will be some scope for additional package managers, but probably after the next release. I'll create a new issue for additional package considerations
