### ISSUE TITLE
[touchbar]: command not working/present

### ISSUE THREAD

**Issue by anshumanv** [rgcr/m-cli#153]
Great tool!

README says there's a touchbar flag but I don't really see it in the commands printed in the cli help, did I miss something?

```
ProductName:	Mac OS X
ProductVersion:	10.15.3
BuildVersion:	19D76 
```

**Comment by bensleveritt** [comment]
You're right, the touchbar support is unreleased. I'll update this issue after release

**Comment by bensleveritt** [comment]
0.3.0 has been released, so I'll close this.
