### ISSUE TITLE
m bluetooth command doesn't work

### ISSUE THREAD

**Issue by vibraniumdev** [rgcr/m-cli#154]
If Bluetooth is on, when one types `m bluetooth status`, it shows: "Bluetooth ON". However, when one types `m bluetooth disable` and enters the password, it shows: "No matching processes were found".

Even though if you type `m bluetooth status`one more time it tells you "Bluetooth OFF", meaning that apparently it worked, the Bluetooth icon on menu bar is still activated.

![Screen Shot 2020-03-03 at 23 31 21](https://user-images.githubusercontent.com/24235344/75839229-1a46f180-5da7-11ea-9ea4-725ebf9c5631.png)

**Comment by bensleveritt** [comment]
Ah, this has been resolved (#126) and will be in the next release

**Comment by bensleveritt** [comment]
0.3.0 has been released, so I'll close this.
