### ISSUE TITLE
homebrew?

### ISSUE THREAD

**Issue by elgs** [rgcr/m-cli#16]
Any chance to install from homebrew?

**Comment by ulyssesv** [comment]
#6 ...

**Comment by renard** [comment]
I just wrote an unofficial recipe for homebrew.

Check this out: https://github.com/renard/homebrew-cw/blob/master/m-cli.rb

Please note that current m-cli is not really suitable for homebrew as it. I needs a few patches.

**Comment by selfagency** [comment]
@renard 

```
» brew install --HEAD m-cli
==> Cloning https://github.com/rgcr/m-cli.git
Cloning into '/Users/daniel/Library/Caches/Homebrew/m-cli--git'...
remote: Counting objects: 39, done.
remote: Compressing objects: 100% (37/37), done.
remote: Total 39 (delta 3), reused 21 (delta 1), pack-reused 0
Unpacking objects: 100% (39/39), done.
Checking connectivity... done.
==> Checking out branch master
==> Patching
patching file m
Hunk #1 FAILED at 1.
1 out of 1 hunk FAILED -- saving rejects to file m.rej
Error: Failure while executing: /usr/bin/patch -g 0 -f -p1
```

**Comment by renard** [comment]
@selfagency As I said `m-cli` is not currently suitable for homebrew.

The problem is here:

````bash
if [ -L $0 ]; then
    pushd `readlink $0 | xargs dirname` > /dev/null
else
    pushd `dirname $0` > /dev/null
fi
````

`readlink` on OSX does not resolve an absolute the path.

I do not want to handle patches over patches it would be nice that @rgcr provides and official handler for relocation.

**Comment by rgcr** [comment]
@renard Thank you so much for your effort here, I'll working on it 👍

**Comment by teddywing** [comment]
For others wondering about the status of the formula: https://github.com/Homebrew/homebrew-core/pull/3137

**Comment by bensleveritt** [comment]
Ace. This can be closed!

**Comment by michaelhood** [comment]
thanks for getting this into homebrew. just installed. 👍

**Comment by rgcr** [comment]
Done ! 😃 
https://github.com/Homebrew/homebrew-core/commit/d4357b9b94e3c5b216f248ab6d7f96b4b42254c6
