### ISSUE TITLE
plugin bluetooth enable doesn't work

### ISSUE THREAD

**Issue by caffeineinc** [rgcr/m-cli#17]
Model Name:	MacBook Pro
Model Identifier:	MacBookPro11,3
Processor Name:	Intel Core i7
Bluetooth   Firmware Version:	v118 c9121

Doesn't enable hardware using  `m bluetooth enable`. reports same as disable, which works fine.

**Comment by rgcr** [comment]
Could you please run this commands and let me know if it works 

1. `sudo defaults write /Library/Preferences/com.apple.Bluetooth ControllerPowerState -int 1`

2. `sudo launchctl unload /System/Library/LaunchDaemons/com.apple.blued.plist`

3. `sudo launchctl load /System/Library/LaunchDaemons/com.apple.blued.plist`

**Comment by rgcr** [comment]
This commit should fix this c4727da, see #49 for further information
