### ISSUE TITLE
Installed but won't work

### ISSUE THREAD

**Issue by Strandbummler** [rgcr/m-cli#24]
USER@HOST:~$ m
-bash: m: command not found

macOS 10.11.5, using iTerm2 Build 3.0.4, but same problem in standard macOS Terminal. Ran the installscript multiple times, always says, already installed. But no luck getting it to work.

Any suggestions?

**Comment by moyaja** [comment]
Having the exact same issue. 
macOS 10.11.5
using Terminal

**Comment by blahah** [comment]
you need to add the install location to your `PATH`:

If you use `bash`:

```bash
echo "export PATH=$PATH:/usr/local/m-cli" >> ~/.profile
```

or you use `zsh`:

```bash
echo "export PATH=$PATH:/usr/local/m-cli" >> ~/.zshrc
```

then open a new terminal, and `m` should be found.

**Comment by Strandbummler** [comment]
path was added successfully, no change. still won't work... :( (bash)

**Comment by blahah** [comment]
What's the output of `ls -alh /usr/local/m-cli` ?

**Comment by Strandbummler** [comment]
USER@HOST:~$ ls -alh /usr/local/m-cli
total 56
drwxr-xr-x  10 user  wheel   340B 15 Jul 11:58 .
drwxr-xr-x  21 user  wheel   714B 15 Jul 11:58 ..
drwxr-xr-x  16 user  wheel   544B 15 Jul 12:07 .git
-rw-r--r--   1 user  wheel    16B 15 Jul 11:58 .gitignore
-rw-r--r--   1 user  wheel   1,1K 15 Jul 11:58 LICENSE.md
-rw-r--r--   1 user  wheel    10K 15 Jul 11:58 Readme.md
-rwxr-xr-x   1 user  wheel   1,7K 15 Jul 11:58 install.sh
drwxr-xr-x   4 user  wheel   136B 15 Jul 11:58 lib
-rwxr-xr-x   1 user  wheel   887B 15 Jul 11:58 m
drwxr-xr-x  27 user  wheel   918B 15 Jul 11:58 plugins

everything is there, i guess

**Comment by theothermattm** [comment]
Having the same issue with the path.  However, when I copy the main script with a name of "m-cli" everything works well.  See the output below.  I'm on OSX 10.11.5.

```
mymac:~ myuser$ ls -alh /usr/local/m-cli/
total 64
drwxr-xr-x  11 myuser  admin   374B Jul 15 08:50 .
drwxr-xr-x  23 myuser  admin   782B Jul 15 08:43 ..
drwxr-xr-x  13 myuser  admin   442B Jul 15 08:43 .git
-rw-r--r--   1 myuser  admin    16B Jul 15 08:43 .gitignore
-rw-r--r--   1 myuser  admin   1.1K Jul 15 08:43 LICENSE.md
-rw-r--r--   1 myuser  admin    10K Jul 15 08:43 Readme.md
-rwxr-xr-x   1 myuser  admin   1.7K Jul 15 08:43 install.sh
drwxr-xr-x   4 myuser  admin   136B Jul 15 08:43 lib
-rwxr-xr-x   1 myuser  admin   887B Jul 15 08:43 m
-rwxr-xr-x   1 myuser  admin   887B Jul 15 08:50 m-cli
drwxr-xr-x  27 myuser  admin   918B Jul 15 08:43 plugins
mymac:~ myuser$ m battery status
battery: No such file or directory
status: No such file or directory
mymac:~ myuser$ m-cli battery status
Now drawing from 'AC Power'
 -InternalBattery-0 	100%; charged; 0:00 remaining present: true Reports To Manager Name & Phone Number
```

**Comment by blahah** [comment]
@Strandbummler OK, so the only other obvious place is the `PATH`. Output of `echo $PATH` ?

**Comment by Strandbummler** [comment]
USER@HOST:~$ echo $PATH
/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:/usr/local/MacGPG2/bin

i think we are getting somewhere, but in ~/.profile it says:
export PATH=/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:/usr/local/MacGPG2/bin:/usr/local/m-cli

**Comment by carambito** [comment]
I got mine to work though this is not as nice.  After installing, I moved the whole directory from the usr/local to User/USER/ and renamed it to '.m-cli'.  Then I went into my .profile and edited the path to be User/USER/.m-cli.

**Comment by scottosmith** [comment]
Just a friendly reminder, make sure you open a new terminal window after these changes. It won't take effect if you haven't yet.

**Comment by blahah** [comment]
@Strandbummler I apologise for my typo in the `echo` command - there should be a `\` before `$PATH` (I've fixed it above now). I recommend deleting that line from `~/.profile` and then re-running the fixed  `echo` command above.

However, this doesn't explain your issue. As @scottosmith says the changes only take affect when the terminal session starts. If you **open a new terminal window** and type `echo $PATH && which m` what do you get?

**Comment by wlin114** [comment]
I found out that my `PATH` is in  .bash_profile not .profile  

So I changed @blahah 's command to  `echo "export PATH=\$PATH:/usr/local/m-cli" >> ~/.bash_profile`

Now `m` works perfectly for me :)

**Comment by rgcr** [comment]
@Strandbummler are you still getting this error? try to install the tool again I've made some changes and now it's not required export the path in your profile, It create a file automatically in /etc/paths.d/m-cli

**Comment by emaxon** [comment]
@wlin114 solution worked for me.

**Comment by rgcr** [comment]
I'm going to close this issue as there is no new news

**Comment by jameshalsall** [comment]
@rgcr can we not create a symlink for `/usr/local/m-cli/m` into `/usr/local/bin` in the install.sh? This would alleviate any path issues people have post-install.

**Comment by rgcr** [comment]
@jameshalsall I think it's a good idea, I've changed this in the latest commit.

**Comment by Strandbummler** [comment]
Since i started the topic, I just wanted to let you know that it works now, at least for me :) Thanks for the effort. I really appreciate it, keep up the good work.
