### ISSUE TITLE
Documentation/Recommendation: /etc/paths.d/m-cli

### ISSUE THREAD

**Issue by JasonJAyalaP** [rgcr/m-cli#31]
The most universal and complete way to set a path variable on OS X (all users, all recent version of OS X, GUI & CLI) is the `/etc/paths.d/` directory. Instead of (or in addition to) the recommendation to put "export $PATH..." inside one of the user profiles, the install process can recommend something like `sudo echo '/usr/local/m-cli' > /etc/paths.d/m-cli`. Or it can be an automatic part of the install process. There are permission issues (in both cases) to iron out, though.

**Comment by rgcr** [comment]
Thank you so much for this, I've implemented this in the latest version 👍 
Now `/etc/paths.d/m-cli` is created during the installation process
