### ISSUE TITLE
Require a password once for certain commands

### ISSUE THREAD

**Issue by clarkio** [rgcr/m-cli#32]
Thanks for putting this utility together it is very helpful. 

Is it be possible to require the password only once instead of having to re-enter it for certain commands? Or is there a limitation/security concern in enabling that functionality that lead to the current implementation?

As an example:
```bash
 $: m hostname
Password:
ComputerName:  [computername]
Password:
HostName:  [hostname]
Password:
...
```

**Comment by clarkio** [comment]
Looked into the source code for `hostname` and came up with something that could work (based on this answer in [SO](http://stackoverflow.com/a/30342433):

```bash
sudo sh -c 'scutil --get ComputerName | awk '\''{print "ComputerName: ", $1}'\''
scutil --get HostName | awk '\''{print "HostName: ", $1}'\''
scutil --get LocalHostName | awk '\''{print "LocalHostName: ", $1}'\''
defaults read /Library/Preferences/SystemConfiguration/com.apple.smb.server NetBIOSName | awk '\''{print "NetBIOSName: " $1}'\'''
```

I imagine there might be a more elegant way of doing this, but I'm still learning bash 😃 

Thoughts?

**Comment by rgcr** [comment]
Hello @clarkio , this is related to sudo and it can be configured in your sudo config file, you should add a line like this one
```
YOURUSER ALL=(ALL) NOPASSWD: ALL
```

And unfortunately most of commands requires permissions

**Comment by clarkio** [comment]
@rgcr thanks for the quick response. 

Sorry for the potentially noob question, but can you elaborate more on what that will do? Does it essentially turn off any need for a password for my user account when root level commands are executed? If so, what if someone prefers a password to still be required for such commands due to security concerns?

**Comment by rgcr** [comment]
@clarkio, You can use PASSWD and NOPASSWD to specify whether the user has to enter a password or not.

And you are right, it will be annoying put the password multiple times, I have to improve that 👍

**Comment by rgcr** [comment]
As a quick workaround I've removed sudo in the commands that show the hostname
