### ISSUE TITLE
`nvarm` error on checking safeboot status

### ISSUE THREAD

**Issue by diego898** [rgcr/m-cli#34]
```
➜  ~ m --update
m-cli Is already installed
Updating m-cli from git
remote: Total 0 (delta 0), reused 0 (delta 0), pack-reused 0
HEAD is now at d0b6f56 Merge 'jfultz-master',we can launch m from a symlink

Done!
➜  ~ m safeboot status
nvram: Error getting variable - 'boot-args': (iokit/common) data was not found
➜  ~
```

**Comment by rgcr** [comment]
Hello @diego898, I think this is an OS X error I found the same fix in multiples foros

> OK, I found a workaround. You must manually add the corresponding variable to nvram by issuing the following command in the terminal:
> 
> sudo nvram boot-args="kext-dev-mode=1"
> Then reboot your Mac.
