### ISSUE TITLE
it doesn't work, it is asking to symlink m, how do i symlink it and to where?

### ISSUE THREAD

**Issue by shaunstanislaus** [rgcr/m-cli#36]
```shell
╰─$ curl -fsSL https://raw.githubusercontent.com/rgcr/m-cli/master/install.sh | sh                                                                                                                  127 ↵
m-cli Is already installed
Updating m-cli from git
remote: Total 0 (delta 0), reused 0 (delta 0), pack-reused 0
HEAD is now at d0b6f56 Merge 'jfultz-master',we can launch m from a symlink
Password:
Password:

Done!
╭─shaunstanislaus@Master  ~ ‹2.3.1›
╰─$ m
zsh: command not found: m
╭─shaunstanislaus@Master  ~ ‹2.3.1›
╰─$
```

**Comment by rgcr** [comment]
@shaunstanislaus Could you please run these commands and share the output
`cat /etc/paths.d/m-cli`
`echo $PATH`

**Comment by varunyellina** [comment]
I'm having the same issue.
```
 12:42:37  ~  ♦️ 2.3.0 
$ cat /etc/paths.d/m-cli
/usr/local/m-cli

 12:42:38  ~  ♦️ 2.3.0 
$ echo $PATH
/Users/varunyellina/.rbenv/shims:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin
```

**Comment by rgcr** [comment]
Hello @varunyellina, do you have the same problem ? 
Seems your path variable is ignoring paths.d files, that's weird. 

Please try to add the path manually and check if it works

`export PATH=${PATH}:/usr/local/m-cli`

**Comment by varunyellina** [comment]
I'm currently using zsh with oh-my-zsh config. Since this isn't the default setting on OSX, does it affect your installation script?

**Comment by rgcr** [comment]
I'm using zsh also and zgen instead oh-my-zsh, so that's not a problem, I think PATH variable is being overwritten in some point.

if that is the reason include this line in your profile and it should work
`export PATH=${PATH}:/usr/local/m-cli`

**Comment by varunyellina** [comment]
It does work when I add `export PATH=${PATH}:/usr/local/m-cli`. I'm not sure how `paths.d` is being ignored.

**Comment by rgcr** [comment]
Maybe it is overwritten in some plugin of oh-my-zsh, you can test it with bash and see if there is the m-cli path

1. `bash`
2. `echo $PATH`

**Comment by varunyellina** [comment]
Without adding to path as you mentioned.
```
 13:11:48  ~  ♦️ 2.3.0 
$ echo $PATH
/Users/varunyellina/.rbenv/shims:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin

 13:11:55  ~  ♦️ 2.3.0 
$ bash
bash-3.2$ echo $PATH
/Users/varunyellina/.rbenv/shims:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin
bash-3.2$
```

Now after adding editing `~/.zshrc` with `export PATH=${PATH}:/usr/local/m-cli`

```
 13:14:27  ~  ♦️ 2.3.0 
$ echo $PATH
/Users/varunyellina/.rbenv/shims:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:/usr/local/m-cli

 13:14:35  ~  ♦️ 2.3.0 
$ bash
bash-3.2$ echo $PATH
/Users/varunyellina/.rbenv/shims:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:/usr/local/m-cli
bash-3.2$
```

I'm confused. How is bash reading `~/.zshrc`?

**Comment by blahah** [comment]
That's happening because bash inherits the environment from zsh, as do all programs executed from within a shell by default.

To see this for yourself:

```bash
~ ❯ export TEST=testing
~ ❯ echo $TEST
testing
~ ❯ bash
0 ✓ ~ $ echo $TEST
testing
```

**Comment by rgcr** [comment]
@blahah you are right, then the thing here is why the shell is not taking the paths from paths.d

**Comment by blahah** [comment]
@rgcr I would guess there's another assignment to `PATH` in a startup script that is overriding those loaded from `paths.d`.

@varunyellina does `.zshrc` contain any other `PATH =` statements?

**Comment by rgcr** [comment]
@blahah I think the same, @varunyellina you can try creating a temporary `.zshrc` file without plugins and check your `PATH` variable again

**Comment by shaunstanislaus** [comment]
@rgcr 
```bash
% export PATH=${PATH}:/usr/local/m-cli                                                                                                                                                                  ~
pyenv: no such command `sh-activate'
% cat /etc/paths.d/m-cli                                                                                                                                                                                ~
/usr/local/m-cli
```

**Comment by rgcr** [comment]
@shaunstanislaus please install the latest version. It creates a symlink instead a paths.d file :)

`curl -fsSL https://raw.githubusercontent.com/rgcr/m-cli/master/install.sh | sh`
