### ISSUE TITLE
Network interfaces should show IP addresses

### ISSUE THREAD

**Issue by dmuth** [rgcr/m-cli#41]
When typing `m network ls`, I get a list of all interfaces and their Mac addresses.

Expected behavior: seeing the current IP addresses as well.  That would be really useful to have for troubleshooting purposes.

**Comment by rgcr** [comment]
`ifconfig` does that, I suppose you want the same functionality but more readeable like the output of `m network ls`,  am I right?

**Comment by dmuth** [comment]
Yeah, I'm good friends with `ifconfig`, but it's way too verbose.  The output from `m` is **quite** readable, and I'd love to see more things like IP addresses in it.

I'll take a whack at the code (not necessarily tonight) and see what I can do.

**Comment by dmuth** [comment]
So I did just take a quick look at the code, and it's written in the Bourne Shell.  I checked into associative arrays in bash, and they're only support in Bash version 4.

Do we have the option of contributing code in a language other than shell?  If so, I'll proceed. (I'm thinking PHP, but more than happy to do Python...)

**Comment by rgcr** [comment]
Hello @dmuth  I think we need to keep it as simple as possible, so I wrote a simple shell function to do it

This is an example of the output:
```
Hardware Port: Wi-Fi
Device: en0
Ip: 192.168.1.1
Ethernet Address: AA:BB:CC:DD:EE:FF


Hardware Port: Bluethoot PAN
Device: en4
Ip: 
Ethernet Address: AA:BB:CC:DD:EE:FF
```

**Comment by dmuth** [comment]
I just looked at your solution code, and wasn't aware of the `ipconfig` command.  Had I know that, I would have used it.  Nice job!

**Comment by tnguyen14** [comment]
@rgcr I just tried using your solution 
```

list_netservices(){
    networksetup -listallhardwareports | while IFS= read -r line; do
        # if it is a device we will print the ip in the next line
        if echo ${line} | grep -i "Device" >/dev/null 2>&1; then
            echo "${line}\nIp: $(ipconfig getifaddr $(echo ${line} | cut -d: -f2 2>/dev/null))"
        else
            echo ${line}
        fi
    done
}
```

I'm seeing this in the output
```
:; list_netservices

Hardware Port: Wi-Fi
Device: en0\nIp: 10.200.13.17
Ethernet Address: 78:31:c1:d0:3f:20

Hardware Port: Bluetooth PAN
Device: en4\nIp:
Ethernet Address: 78:31:c1:d0:3f:21

Hardware Port: Thunderbolt 1
Device: en1\nIp:
Ethernet Address: 72:00:02:b4:7b:20
```

I'm guessing the `\n` is not formatted correctly?

**Comment by rgcr** [comment]
hello @tnguyen14, try to use `printf` instead `echo`
```sh
list_netservices(){
    networksetup -listallhardwareports | while IFS= read -r line; do
    # if it is a device we will print the ip in the next line
    if echo ${line} | grep -i "Device" >/dev/null 2>&1; then
        #echo "${line}\nIp: $(ipconfig getifaddr $(echo ${line} | cut -d: -f2 2>/dev/null))"
        printf "${line}\nIP:$(ipconfig getifaddr $(echo ${line} | cut -d: -f2 2>/dev/null))\n"
    else
        #echo ${line}
        printf "${line}\n"
    fi
done

}
```

**Comment by tnguyen14** [comment]
@rgcr that works great. thanks!

**Comment by REBELinBLUE** [comment]
In the latest version I am not getting the newline, rather the escape character

```
Hardware Port: Targus USB3 DV1K-2K Compact Doc
Device: en7\nIp: 10.152.29.116
Ethernet Address: 00:50:b6:cc:46:23
```

**Comment by rgcr** [comment]
Hello @REBELinBLUE  I've changed this to use `printf` instead `echo` in the latest version  (v0.1.8), it should work now
