### ISSUE TITLE
vpn start does not work on El Capitan

### ISSUE THREAD

**Issue by yannickulrich** [rgcr/m-cli#53]
When I start VPN I get an error from AppleScript

```bash
$ m vpn start <name>
missing value
```

I'd use `scutil --nc start "$1"` instead. Do you want me to file a pull request?

By the way, great projects!

Cheers

**Comment by rgcr** [comment]
Hello, this commit should fix this 0f9b3459dfd71ff872e1da5baa83f68a98563f29, please test it and reopen the issue if something is wrong 👍
