### ISSUE TITLE
Gif for README

### ISSUE THREAD

**Issue by rgcr** [rgcr/m-cli#54]
![demo](https://cloud.githubusercontent.com/assets/1203422/16932455/0446ae66-4d0c-11e6-82a5-8bf9b2a3ab75.gif)

**Comment by IzzyBzMom1** [comment]
![image](https://cloud.githubusercontent.com/assets/20372167/16969936/90c54fe8-4de6-11e6-9bf0-ddd1e70937c7.png)
![image](https://cloud.githubusercontent.com/assets/20372167/16969937/90d44890-4de6-11e6-8250-f49d59ac298b.png)
