### ISSUE TITLE
Prompt for password (vpn, wifi etc.)

### ISSUE THREAD

**Issue by ringvold** [rgcr/m-cli#55]
Hi!

Just recently found this tool and find it very nice. No longer need to remember the weird commands in OSX to configure it is great! Thanks!

Have you considered an option for getting a prompt to type in the password instead of having to have it in the command?
I'm no talking about the admin password but for example when connecting to VPN or wifi.

**Comment by rgcr** [comment]
It's a great idea 👍 I'll keep it in mind for the next versions :)
