### ISSUE TITLE
VPN: unrecognized option `--pasword'

### ISSUE THREAD

**Issue by huanzhang** [rgcr/m-cli#57]
I got the following error~

➜  ~ m vpn start 8CB2849B-5EC3-4F80-88E5-02E41CD9BA7A 'user' 'mypass'
scutil: unrecognized option `--pasword'
usage: scutil
        interactive access to the dynamic store.

   or: scutil --prefs [preference-file]
        interactive access to the [raw] stored preferences.

   or: scutil [-W] -r nodename
   or: scutil [-W] -r address
   or: scutil [-W] -r local-address remote-address
        check reachability of node, address, or address pair (-W to "watch").

   or: scutil -w dynamic-store-key [ -t timeout ]
        -w      wait for presense of dynamic store key
        -t      time to wait for key

   or: scutil --get pref
   or: scutil --set pref [newval]
   or: scutil --get filename path key
        pref    display (or set) the specified preference.  Valid preferences
                include:
                        ComputerName, LocalHostName, HostName
        newval  New preference value to be set.  If not specified,
                the new value will be read from standard input.

**Comment by rgcr** [comment]
Hello @huanzhang, Could you please let me know what is the output if you run this `m info`?

**Comment by huanzhang** [comment]
@rgcr here is the output below:
➜  kt-lode git:(master) m info
ProductName:    Mac OS X
ProductVersion: 10.11.5
BuildVersion:   15F34

**Comment by rgcr** [comment]
I found the error, it's fixed. Please update the tool `m --update` 👍

**Comment by huanzhang** [comment]
@rgcr 👍
