### ISSUE TITLE
Introduce Brew Package

### ISSUE THREAD

**Issue by electic** [rgcr/m-cli#6]

**Comment by renard** [comment]
See #16 for an unofficial brew recipe

**Comment by rgcr** [comment]
Done ! 😄 
https://github.com/Homebrew/homebrew-core/commit/d4357b9b94e3c5b216f248ab6d7f96b4b42254c6

**Comment by whyfuture** [comment]
==> Caveats
Bash completion has been installed to:
  /usr/local/etc/bash_completion.d

How to implement this into fish shell?

**Comment by electic** [comment]
How does one install it? I updated to the latest homebrew and the recipe is not there.

**Comment by whyfuture** [comment]
@electic 
do `brew update` at first

**Comment by rgcr** [comment]
Hello @whyfuture, I'll try to work on it 😅  please feel free to create a PR or an issue for this.

**Comment by electic** [comment]
@whyfuture I did the update. I get this:

code/
➔ brew install mcli
Error: No available formula with the name "mcli"
==> Searching for similarly named formulae...
Error: No similarly named formulae found.
==> Searching taps...
This formula was found in a tap:
Caskroom/versions/mpeg-streamclip-beta
To install it, run:
  brew install Caskroom/versions/mpeg-streamclip-beta

**Comment by twe4ked** [comment]
@electic The formula is called `m-cli`.

**Comment by electic** [comment]
Ah, thanks :) Solved.
