### ISSUE TITLE
add keyboard command

### ISSUE THREAD

**Issue by doodzik** [rgcr/m-cli#60]
I would like to know if there is interested in a keyboard command.
If there is I can add it
To switch keyboard layouts, (like https://github.com/Lutzifer/keyboardSwitcher (this is written in obj-c))
To set custom mappings for mapping keys
And to change the general keyboard settings
(ref https://github.com/doodzik/osx_init/blob/master/system_config.sh#L19-L30)

**Comment by rgcr** [comment]
Both ideas are great but I think we should keep it as simple as possible(using scripting and native osx commands).  I think it's not a good idea to include a 3rd party tool.

I would like to hear your opinion.

**Comment by doodzik** [comment]
Yeah. I think you are right there.
[I know that you can't change your current keyboard layout by changing the config.
What do you think about using applescript to change it in the menu bar and a command to add them there?](http://stackoverflow.com/a/23741934)

**Comment by rgcr** [comment]
It it works then please go ahead 👍

**Comment by doodzik** [comment]
👍 

I will probably push different changes before I have time to develop this.

**Comment by doodzik** [comment]
The usecase for this command isn't relavant for me anymore so I close this. Because I won't work on it.
