### ISSUE TITLE
Zsh completion error

### ISSUE THREAD

**Issue by Leeds-eBooks** [rgcr/m-cli#63]
If I type `m <tab>`, in zsh, I'm getting the following:
```
_m:2: unknown file attribute: \n
_m:2: unknown file attribute: \n
```

Any ideas? Some googling brings up something about zsh arrays not being the same as bash arrays but I'm not sure that's the problem here. Sorry for not giving more information but I'm not what would be helpful – so please let me know. Thanks very much!

**Comment by Leeds-eBooks** [comment]
`which _m` returns:
```
_m () {
	local -a opts
	local commands=(
        help
        "--update:update m-cli to the latest version"
        "--uninstall:uninstall m-cli"
        "battery:get the battery status"
        "bluetooth:manage bluetooth status"
        "dir:show and delete dir trees"
        "disk:manage disks and volumes"
        "dns:manage dns"
        "dock:manage dock"
        "finder:manage finder properties"
        "firewall:manage firewall"
        "gatekeeper:manage gatekeeper (security for apps)"
        "group:manage groups"
        "hostname:displays or set the computer's hostname"
        "info:print Mac OS X operating system version information"
        "lock:lock session"
        "network:manage interfaces and locations"
        "nosleep:prevent sleeping"
        "ntp:manage the network time service"
        "restart:restart computer"
        "safeboot:manage safeboot"
        "screensaver:launch and manage the screensaver"
        "service:manage services"
        "shutdown:shutdown computer"
        "sleep:put the computer to sleep"
        "timezone:manage timezone"
        "trash:manage the trash"
        "user:manage users"
        "update:manage OS X updates"
        "volume:manage the sound's volume"
        "vpn:basic vpn operations, start, stop, status, list"
        "wallpaper:set the wallpaper"
        "wifi:manage the wifi"
    )
	case $CURRENT in
		(2) _describe 'm commands' opts -- commands ;;
		(*) local sub=${words[2]}
			_m_cmd $sub ;;
	esac
}
```

**Comment by rgcr** [comment]
Hello @Leeds-eBooks, that's weird, please try to delete the zcompdump files and reload your teminal
`rm -f ~/.zcomp*`

**Comment by Leeds-eBooks** [comment]
Thanks for your response! I ran that exact command, verified the files were gone, reloaded the terminal, but the error persists:

<img width="267" alt="screen shot 2016-08-01 at 18 41 57" src="https://cloud.githubusercontent.com/assets/4380655/17303266/cbb63cb2-5817-11e6-99dd-8a337ef203fd.png">

If it's any help, the number of occurrences of the error differ based on what's already typed when I press `tab`.

**Comment by Leeds-eBooks** [comment]
Maybe it is how I am loading the completion script. As homebrew installed it into `/usr/local/share/zsh/site-functions`, but my zsh looks in `/usr/share/zsh/site-functions`, I added the following line at the top of my `.zshrc`:
```
fpath=(/usr/local/share/zsh/site-functions $fpath)
```

**Comment by rgcr** [comment]
Hello @Leeds-eBooks, it's fixed, I will update the brew formula with this fix

**Comment by Leeds-eBooks** [comment]
@rgcr Brilliant, thanks!

It works now, but having another related issue:

```
~ ❯ m battery <tab>
_m_solo:4: number expected
_m_solo:4: number expected
```

**Comment by rgcr** [comment]
@Leeds-eBooks , thank you so much for this information, it's fixed now 👍

**Comment by Leeds-eBooks** [comment]
Great, thanks :) will you update the homebrew package soon?

**Comment by rgcr** [comment]
I have a PR opened in `brew` as soon as they merge the PR it will be updated 👍

**Comment by Leeds-eBooks** [comment]
I can confirm that it's working on my end now.
