### ISSUE TITLE
Add completions for FISH shell

### ISSUE THREAD

**Issue by whyfuture** [rgcr/m-cli#64]
Please add auto-completions for the majestic [FISH](https://github.com/fish-shell/fish-shell/) shell.

**Comment by sdaitzman** [comment]
Commenting so I get notified 👍

**Comment by rgcr** [comment]
I added a simple completion for `fish` c298b0c, I have never used `fish` before, I'll improve this soon so I'll keep this issue opened. Also I'll update the `brew` formula to have this completion available.

**Comment by sdaitzman** [comment]
@rgcr how do we add the completions to Fish? Where do they get installed to/where can we source them from?

**Comment by rgcr** [comment]
@sdaitzman Sorry for the late response, the latest version should contain the fish completion, also you can copy the `completion/fish/m.fish` file to `~/.config/fish/completions/`

**Comment by floam** [comment]
It looks like your fish completions have an error with an empty argument for a description  - see https://github.com/fish-shell/fish-shell/issues/3557#issuecomment-260873276

**Comment by rgcr** [comment]
@floam, done. Thank you 👍

**Comment by bensleveritt** [comment]
Closing, as I *think* this is done... Feel free to raise any specific Fish completions that are missing.
