### ISSUE TITLE
m-cli update with homebrew install

### ISSUE THREAD

**Issue by fergstar** [rgcr/m-cli#66]
Can not update homebrew installed m-cli, getting message that not a git repository.
I run the command 'm --update' and it shows the following:
```
> m --update
m-cli is already installed
Updating m-cli from git
fatal: Not a git repository: '/usr/local/Cellar/m-cli/0.1.0/.git'
Failed to fetch changes => https://github.com/rgcr/m-cli.git
```

Which I would assume that I should use 'brew upgrade m-cli' if I installed it with homebrew. Just thought I would advise on the error message when I try to upgrade via m-cli

**Comment by rgcr** [comment]
Hello @fergstar you are right, I have to disable these options when the package is installed via `homebrew`. I'm working on it.

**Comment by rgcr** [comment]
Homebrew/homebrew-core/pull/3579

**Comment by rgcr** [comment]
Now those options are disabled if `m-cli` is installed via `brew`. It should show a brief help to do it with `brew`
