### ISSUE TITLE
m disk repair volume does not recognize escaped spaces

### ISSUE THREAD

**Issue by sdaitzman** [rgcr/m-cli#76]
<img width="407" alt="screen shot 2016-08-12 at 11 39 19 am" src="https://cloud.githubusercontent.com/assets/1499476/17628052/9329b730-6081-11e6-8fcb-fd4a29b62a56.png">
Markdown version of the important parts of the above image:
```bash
$ m disk repair volume /Volumes/DRIVE\ D/
Unable to find disk for /Volumes/DRIVE
```

**Comment by sdaitzman** [comment]
Notes:
- I'm running macOS 10.12 build 16A286a
- I'm using Fish Shell, version 2.3.1
- I updated m-cli within the past day

**Comment by rgcr** [comment]
I'll take a look, thank you so much.

**Comment by rgcr** [comment]
Please update the tool to the latest version, feel free to reopen the issue if you have any problem.
