### ISSUE TITLE
I have an 'alias m='man' in my vimrc, can I somehow use this utility with that alias intact?

### ISSUE THREAD

**Issue by nikitavoloboev** [rgcr/m-cli#77]
I really like having to open manual pages by simply typing `m bash` or something like it. I really like these utilities but they all start with an m. Is there a way I can change this first 'm' to something else and keep my alias for man pages?

Thank you for any help.

**Comment by rgcr** [comment]
If you used `brew` install it you can create an alias like this one `alias mcli='/usr/local/bin/m'`

**Comment by nikitavoloboev** [comment]
thank you, this works
