### ISSUE TITLE
drying up the autocompletion code

### ISSUE THREAD

**Issue by doodzik** [rgcr/m-cli#80]
This project offers now 3 different completion solutions. IMO we should look into removing that repetition.

Does anyone have a suggestion for tackling this problem?

**Comment by rgcr** [comment]
Hello @doodzik, what do you mean, sorry but I can't understand :/ do you think we need to merge the 3 completions in some kind of script to generate them or something like that ?

**Comment by doodzik** [comment]
That would be the way that I would go. And building them at installation time.
I'm not sure if someone build a solution for this problem or if it is even feasible.
@rgcr what are your thoughts on this?

**Comment by rgcr** [comment]
It would be awesome 👍 feel free to create a PR

**Comment by doodzik** [comment]
Unfortunatly I don't have time for this at the moment.
