### ISSUE TITLE
Feature: No Sleep (Caffeinate) with PID

### ISSUE THREAD

**Issue by adkafka** [rgcr/m-cli#99]
This is a simple feature request. I find that after I begin a script, I realize I would like to use 'm nosleep until' on that process. I can do that with caffeinate by running 'caffeinate -w PID'. I think it would be nice to support that feature in m-cli.

I would be happy to make a pull request with this addition, but I am not sure how best to add the feature. As of now, 'm nosleep until NUMBER' will not sleep for NUMBER seconds. There would need to be a way to specify that the number is a PID. Perhaps, prefixing the number with a + or some other character? Backwards compatibility should not be broken. 

Let me know what you think. Like I said, I would be happy to make a pull request with the changes. I really enjoy using this tool and would love to contribute to it!

**Comment by rgcr** [comment]
Hello @adkafka, I added a new subcommand  `m nosleep until pid` also I added the properly completion for `zsh`. It's still pending to improve `bash` and `fish` completions for this.
